
k3s_version = 'v1.18.10+k3s2'

Vagrant.configure(2) do |config|
    #config.vm.box = 'generic/debian10'
    #config.vm.box = 'generic/ubuntu1804'
    config.vm.box = 'hashicorp/bionic64'

    #config.vm.boot_timeout = 600

    # Customize the disk size on the guest VM: (using vagrant-disksize plugin)
    config.disksize.size = '80GB'

    #config.ssh.insert_key = false

    config.vm.provider 'virtualbox' do |vb|
        vb.linked_clone = true
        vb.cpus = 2
        vb.memory = 2048
    end

    # config.vm.hostname = "server1.example.dev"
    config.vm.network :private_network, ip: '10.1.0.101'

    #Waiting for node vagrant CIDR not assigned yet

    #ssh-keygen -t rsa -b 4096 -C "admin@example.dev"
    #cat ~/.ssh/id_rsa.pub | tee -a ~/.ssh/authorized_keys
    #export IP=10.1.0.101
    #k3sup install --ip $IP --user vagrant --k3s-version v1.18.10+k3s2
    # config.vm.provision "install k3s", type: "shell", privileged: false do |script|
    #     script.env = {
    #         "k3s_version" => k3s_version,
    #     }
    #     script.inline = <<-SHELL
    #         echo k3s_version=${k3s_version}
    #         curl -sfL https://raw.githubusercontent.com/rancher/k3s/${k3s_version}/install.sh | INSTALL_K3S_VERSION="${k3s_version}" sh -
    #     SHELL
    # end
end
